USE test;

-- CREATE TABLE PAYMENT_DETAILS (
--     PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
--     FIRST_NAME VARCHAR(50) NOT NULL,
--     SECOND_NAME VARCHAR(100) NOT NULL,
--     ZIP_CODE VARCHAR(15) NOT NULL,
--     CARD_NUMBER VARCHAR(500) NOT NULL,
--     PRIMARY KEY (PAYMENT_ID)
-- );
--
-- CREATE TABLE WEBHOOK (
--     WEBHOOK_ID INT NOT NULL AUTO_INCREMENT,
--     URL VARCHAR(255) NOT NULL,
--     WEBHOOK_TYPE VARCHAR(50) NOT NULL,
--     PRIMARY KEY (WEBHOOK_ID)
-- );
--
-- CREATE TABLE FAILED_WEBHOOK (
--     FAILED_WEBHOOK_ID INT NOT NULL AUTO_INCREMENT,
--     PAYMENT_ID INT NOT NULL,
--     WEBHOOK_URL VARCHAR(255) NOT NULL,
--     WEBHOOK_EXCEPTION VARCHAR(255) NOT NULL,
--     FAILED_AT DATETIME,
--     PRIMARY KEY (FAILED_WEBHOOK_ID)
-- );

INSERT INTO PAYMENT_DETAILS (PAYMENT_ID, FIRST_NAME, SECOND_NAME, ZIP_CODE, CARD_NUMBER) VALUES (1, 'Oisin', 'Marron', 'NSW 2033', 'hPWEu+ufgH8AtPQ8pYsK/DF2uVC+HLOU+Nhg9pEUgfg=');
INSERT INTO WEBHOOK (WEBHOOK_ID, URL, WEBHOOK_TYPE) VALUES (1, 'https://webhook.site/8249ead2-2c15-4281-9610-81b3af4cb7b2', 'NEW_PAYMENT');
INSERT INTO FAILED_WEBHOOK (FAILED_WEBHOOK_ID, PAYMENT_ID, WEBHOOK_URL, WEBHOOK_EXCEPTION, FAILED_AT) VALUES (1, 1, 'https://webhook.site/8249ead2-2c15-4281-9610-81b3af4cb7b2', 'Exception123', '2025-03-13 08:27:40');
